banking_dbt:
  outputs:
    dev:
      account: nn77073.uk-south.azure
      database: banking
      password: Pavani@21061991
      role: accountadmin
      schema: analytics
      threads: 4
      type: snowflake
      user: PSATHRAM
      warehouse: compute_wh
  target: dev
